language: java

branches:
  only:
    - master

before_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

script:
  - mvn clean install cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_failure: change
    on_success: change
